language: node_js
node_js:
  - '12'

install:
  - yarn

script:
  - yarn workspace bloomreach-experience-react-sdk lint
  - yarn build

deploy:
  edge: true
  provider: npm
  cleanup: false
  src: packages/sdk
  api_token: $NPM_AUTH_TOKEN
  on:
    branch: master
    tags: true
